repos:
- repo: local
  hooks:
    - id: black-check
      name: black-check
      entry: black .
      language: system
      types: [ python ]
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      types: [ python ]
      pass_filenames: false
    - id: pylint-check
      name: pylint-check
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "--ignore-paths",
          "tests/",
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]